language: csharp
solution: Cottle.sln
install:
  - nuget restore Cottle.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory tests
script:
  - xbuild /p:Configuration=Release Cottle.sln
  - mono ./tests/NUnit.Console.3.0.1/tools/nunit3-console.exe ./Cottle.Test/bin/Release/Cottle.Test.dll
  - nuget pack -Prop Configuration=Release -Prop Platform=AnyCPU ./Cottle/Cottle.csproj
